### ISSUE TITLE
Doesn't work in Firefox

### ISSUE THREAD

**Issue by dmk12** [RRutsche/react-parallax#1]
Hi, thanks so much for making this! Works like a charm in Chrome and Safari, the only problem seems to be Firefox - I don't see the scrolling effect happening there.

**Comment by rrutsche** [comment]
@dmk12
Hi, thanks for your message. Should also work in firefox now.

**Comment by damienleroux** [comment]
Hey,

The last version doesn't work on Firefox.

`translate3d()` second parameter always stays at `0px` in the style of the html tag with class `react-parallax-content`:

```
<img class="react-parallax-bgimage" src="http://localhost:3001/dist/d03b25a54f9cc83bb48193292fee6997.jpg" alt="" style="height: auto; width: 100%; transform: translate3d(-50%, 0px, 0px); position: absolute; left: 50%; backface-visibility: hidden;">
```

Any idea ? 
Regards

**Comment by rrutsche** [comment]
@damienleroux Thanks for your hint. [v1.0.3](https://github.com/RRutsche/react-parallax/releases/tag/v1.0.3) fixes the firefox issue.

Best regards

**Comment by rrutsche** [comment]
@damienleroux v1.0.3 did not update the minified files. [v1.0.4](https://github.com/RRutsche/react-parallax/releases/tag/v1.0.4) it is ;-)

Best regards

**Comment by damienleroux** [comment]
Thank you it works now :)
