### ISSUE TITLE
Parallax image is not responsive

### ISSUE THREAD

**Issue by sametyildizeli** [RRutsche/react-parallax#107]
Hello,

Height of the image is not responsive when i lower the width pixels, the component gives white spaces on the top and bottom sides beucase i need to give a height parameter for image.

**Comment by sametyildizeli** [comment]
i've fixed with this 
"  background-attachment: fixed;
    background-repeat: no-repeat;
    background-size: 100% auto;
    height: calc(40vw - 10vh);"

**Comment by rrutsche** [comment]
Great to here that you fixed it.
