### ISSUE TITLE
Need support for React 15.0.1

### ISSUE THREAD

**Issue by ateev** [RRutsche/react-parallax#11]
@RRutsche  Can we update this package to use React 15.0.1 ? After upgrading React, i am getting this error. 

```
addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component\'s render method, or you have multiple copies of React loaded.

```

[Link](https://gist.github.com/jimfb/4faa6cbfb1ef476bd105)

**Comment by rrutsche** [comment]
@ateev Thanks for your feedback. I merged your pull request.

**Comment by ateev** [comment]
@RRutsche Can you please release this new one on npm fast ?

**Comment by rrutsche** [comment]
Already did. It's version 0.4.3
