### ISSUE TITLE
Package installation using npm

### ISSUE THREAD

**Issue by MahdiMbarki** [RRutsche/react-parallax#116]
**Describe the bug**
Cannot Install the package using npm

_**$ npm i react-parallax       
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: client@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.x.x || 17.x.x" from react-parallax@3.3.0        
npm ERR! node_modules/react-parallax
npm ERR!   react-parallax@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\sofiene feki\AppData\Local\npm-cache\eresolve-report.txt for a full report.**_

**Comment by rrutsche** [comment]
React 18 is not supported yet. I have to add it.

**Comment by rrutsche** [comment]
React 18 is now added to the list of peer dependencies.
Try again.
