### ISSUE TITLE
parallax component hides other element due to z-index issue.

### ISSUE THREAD

**Issue by feluxe** [RRutsche/react-parallax#13]
Thanks for the great component!

I have one issue though.. I have a button  on my page with a `z-index` of `9999`. If I add the parralallax component the button disappears. The strange thing is, that the button is quite far away from the visible part of the parallax component. If I put a z-index on `div.react-parallax` the button becomes visible again and everything looks fine. So I thought, maybe it would be nice to have a `zIndex` prop for the parallax component? This might be helpful in other cases too.

**Comment by rrutsche** [comment]
Hi @feluxe. Thanks for using the component and for your feedback! Do you have an example online? I just tried to reproduce your issue by adding a `div` with `position: fixed` to the top right of a test page. I also added a `z-index: 10`. But this looked okay to me. 
I think giving your `Parallax` component a custom `className` and setting the `z-index` in CSS is better than adding an extra `zIndex` `prop`. This is also more flexible for other issues. 
Could this solve your problem? Please let me know if not. Currently I'm on vacation so answers will have a little delay ;-)

**Comment by rrutsche** [comment]
@feluxe I will close the ticket as I assume the issue could be fixed otherwise. Please send a message if not. 
Thanks

**Comment by feluxe** [comment]
Sorry for my late response!

> I think giving your Parallax component a custom className and setting the z-index in CSS is better than adding an extra zIndex prop. This is also more flexible for other issues. 

I just solved it like that. Works fine now. If I get more troubles from the issue I'll try to upload an example, but for now the fix works just fine. As long as no one else reports a similar issue and due to the strange behavior I would say it's just a unique bug in my page - nothing to worry ;-)
