### ISSUE TITLE
Custom Background top is cut off

### ISSUE THREAD

**Issue by chrisdobler** [RRutsche/react-parallax#14]
I've been having an issue with the custom background element. I'll try to explain the best I can.

It seems that when you set a custom background element the y coordinate position is off by -158px making the image appear to be cut off and pushed to the top of the frame.

translate3d(-50%, -158px, 0px) always seems to start at -158 at strength 300 no matter the size of the image, but I think it should start at 0px or something lesser than that.

I've included an image to show what I'm talking about https://s3.amazonaws.com/chrisdobler/Screen+Shot+2016-09-12+at+2.37.48+PM.png

I have it set up like this:

```

            <Parallax strength={300}>
              <Background>
                <img src="http://www.fillmurray.com/400/300"/>
              </Background>
              <Rectangle aspectRatio={[16, 6]}></Rectangle>
            </Parallax>
```

**Comment by rrutsche** [comment]
@chrisdobler 
Thanks for your feedback. I will have a look at it. 
I'm anyway working on a calculation enhancement for the background image/component position. 
I will keep you posted.

**Comment by chrisdobler** [comment]
Thanks @RRutsche looking forward to seeing it. Your component is literally the only one that works in a server rendering environment.

Another thing I noticed is that the background position seems to move when I change the window size, which I guess has something to do with my issue. Is there any way currently to make the background's position relative to the parent div rather than the window?

**Comment by damienleroux** [comment]
- 1. I have the same issue.

This seem to come from [this line](https://github.com/RRutsche/react-parallax/blob/master/src/jsx/Parallax.jsx#L179):

```
Math.floor(((top + this.contentHeight - 0.25*this.props.strength) / this.windowHeight) * this.props.strength) * -1;
```

For example, if a window with a height of 200px begins with a Parallax using a strength of 400, I got a margin-top effect of 200 px. This "margin" change when resizing the window.

Any help will be greatly appreciated :)

**Comment by rrutsche** [comment]
@damienleroux Calculation enhancement is nearly finished. It just needs a bit more testing.
In the calculation branch I located the issue and fixed the top position of both the `Parallax` component and the custom `Background` component. I replaced the calculation line you mentioned and the one for `Background` Component entirely.

I will merge it to master in the next days. Thanks for your feedback.

**Comment by damienleroux** [comment]
Thank you a lot for sharing. I'll wait your next version and be happy to test it. Thank you

**Comment by rrutsche** [comment]
@chrisdobler @damienleroux I just published the new version. I hope it solves your issue.

**Comment by damienleroux** [comment]
ok I am going to test it. Thank you

**Comment by damienleroux** [comment]
All works very fine and I have not the 'top' problem anymore. Thank you!! Great Job!

**Comment by rrutsche** [comment]
Super! If you find any other issue, let me know.
