### ISSUE TITLE
bgHeight doesn't appear to work

### ISSUE THREAD

**Issue by cyberwombat** [RRutsche/react-parallax#16]
If I try this (0.4.5)

```
 <Parallax bgImage={image} strength={400} bgHeight='200px'/>
```

I get nothing. If I add content it stays just big enough to accommodate.

**Comment by rrutsche** [comment]
Hi @cyberwombat,
thanks for your feedback. Do you want to resize the `Parallax` component itself? The `bgHeight` prop is meant to set just the size of your background image not the whole component. To achieve this you have to steer it with the content itself or with custom `css`.

**Comment by cyberwombat** [comment]
Yes. I thought it controlled the height of the container. Thanks for clarifying.
