### ISSUE TITLE
Access to inline styles of the .react-parallax-background-children class

### ISSUE THREAD

**Issue by devdua** [RRutsche/react-parallax#17]
Hi

Is there a way to adjust the CSS styles that are used inline when the component renders? The default values are causing considerable clipping in my image file, and I can't seem to find a way to adjust it via any other means. For example, the `left` value has been set as 50% but I see that if I set it to 40% (using the DevTools in Chrome), the image renders almost the way I want it to.

Thanks!

**Comment by rrutsche** [comment]
Hi @devdua,
thanks for your feedback. I just added a new prop `bgStyle` with version [1.1.0](https://github.com/RRutsche/react-parallax/releases/tag/v1.1.0) that can pass style values to the background layer in addition to the styles that are already set. The existing style props will be overridden. Let me know if this is working for you.

**Comment by devdua** [comment]
Thanks a lot @RRutsche found no problems so far, this works for me! Cheers!
