### ISSUE TITLE
Smooth scrolling with more than one image

### ISSUE THREAD

**Issue by izziaraffaele** [RRutsche/react-parallax#2]
Adding 2 parallax sections with different images the parallax effect becomes lot less "smooth" than before. When I scroll there is a bit of re-rendering/lagging that makes the scroll behavior not smooth. 

I don't know how to provide an example of the problem I'm facing and I hope you'll be able to help me solving it. 

Maybe would be nice to implement some of the suggestions here? http://kristerkari.github.io/adventures-in-webkit-land/blog/2013/08/30/fixing-a-parallax-scrolling-website-to-run-in-60-fps/

**Comment by izziaraffaele** [comment]
FPS for me are alway below 60. I also do not have such big painting bars in my Chrome console except a big bar when an image gets on the viewport. Really don't get why this strange behavior...

**Comment by rrutsche** [comment]
@izziaraffaele thanks for your feedback. Tested the component with three different instances and images and did not notice lagging. But I'll have a look at it. Maybe I can improve handling of not-visible elements.

Do you have an example online?

**Comment by izziaraffaele** [comment]
Not yet... Here you have a short video showing the issue I'm talking about http://we.tl/CsDJXjQEME. I noticed it on the demo page as well, on the first image so I'm not sure it's a problem related with my images or my html structure. 

I'm using chrome if this can help

**Comment by rrutsche** [comment]
Could reproduce it somehow by adding 3-4 parallax instances with big images to the DOM and putting a huge amount of child props inside the component.

Tried to get rid of the little flickering by updating positions inside requestAnimationFrame plus only if the parallax component is inside viewport. Also locked the min duration between position updates to at least 10 millis. 

And I added some CSS enhancements like `WebkitTransformStyle` and `WebkitBackfaceVisibility` to the translated image.

Hope this helps.

**Comment by izziaraffaele** [comment]
Thanks but actually it didn't solved the problem although I just noticed that on live environment scrolling is a bit more smooth. 

I'll give a look at it now and let you know if I solve the problem

**Comment by izziaraffaele** [comment]
@RRutsche I wasn't able to find the issue but I managed to solve my personal problem. Minifing the images ( with imagemin ) reduced the problem for me. That's why in production was working better... 

I had the strenght parameter set to 500 and that was screwing the component even more. Putting it back to 300 gave me the perfect result.

**Comment by rrutsche** [comment]
@izziaraffaele Glad to hear that you found a solution. 
The original image size should also be as close as possible to the displayed image size when its gonna be translated. I read about some similar issues that occur when these sizes diverge to much.
