### ISSUE TITLE
Cannot read property 'children' of undefined 

### ISSUE THREAD

**Issue by Bram-Zijp** [RRutsche/react-parallax#24]
While having no children in the parallax element you get this error:
`Uncaught TypeError: Cannot read property 'children' of undefined`

**Comment by Bram-Zijp** [comment]
It actually also happens with children. This line errors: 
`value:function(e){var t=[],n=u.default.Children.toArray(e.children);`

**Comment by rrutsche** [comment]
@Bram-Zijp Thanks for the feedback. Will have a look at the issue.

**Comment by rrutsche** [comment]
@Bram-Zijp Which React version are you using? I cannot reproduce the issue. The original line is this one:

```React.Children.toArray(props.children)```

This means React is not defined.

**Comment by Bram-Zijp** [comment]
I found the issue. It had to do with remainings of another parallax module. I'm sorry for the inconvenience.
