### ISSUE TITLE
React-parallax Prompt HTMLDocument is not defined

### ISSUE THREAD

**Issue by qufei1993** [RRutsche/react-parallax#29]
Execute the command: npm run dev
The following error:

## ReferenceError: HTMLDocument is not defined

**Comment by rrutsche** [comment]
Ok, I will have a look. Think it's related to #25.

**Comment by qufei1993** [comment]
When I change the index.js the file,He will be able to work. How to better solve the problem Rather than to modify the file after each installation @RRutsche

**Comment by drbruddet** [comment]
Hey guys, got the same error, I placed the parallax in a component, when I'm calling it like 2 times it works, 3 times doesn't work, it really random.

**Comment by qufei1993** [comment]
Then you need to repair，Site use of this component now

**Comment by rrutsche** [comment]
@Q-Angelo @guillaumeko The bug is fixed in version 1.2.8.
Please check if it also works for you.

**Comment by qufei1993** [comment]
@RRutsche  Good!

**Comment by drbruddet** [comment]
It seems to work great for me! Thank you very much :)

**Comment by rrutsche** [comment]
top. thanks. than I can close the issue
