### ISSUE TITLE
Support React 15.5

### ISSUE THREAD

**Issue by rubenspgcavalcante** [RRutsche/react-parallax#30]
Now the use of the PropTypes from the react packages is deprecated. React points the use of the prop-types package:

    Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Thanks in advance!

**Comment by rubenspgcavalcante** [comment]
Hey @RRutsche , sorry to open this again, but did you run the build process before publish on npm?
I'm having the same problem with the version 1.4.0 when using the dist. bundle. But when I use directly from the source code (node_modules/react-parallax/srx/jsx/index) runs ok. I've checked the source code and the use of the 'prop-types' packages is there, but I think is not being used in the bundled script. 😕

**Comment by rrutsche** [comment]
@rubenspgcavalcante I will have a look later today. Thanks for telling me

**Comment by rrutsche** [comment]
@rubenspgcavalcante I just built version 1.4.1 which fixes the warning. Problem was that the `prop-types` package was not declared as external in the webpack config and so was also compiled by babel.

**Comment by rubenspgcavalcante** [comment]
Alright! Thanks! :)
