### ISSUE TITLE
is blur prop working?

### ISSUE THREAD

**Issue by tuguScript** [RRutsche/react-parallax#32]
i've passed blur prop. My background has no change. are you sure it's working?

**Comment by rrutsche** [comment]
@tuguScript Yes, it is working. Can you show me a snippet so I can see how you are using it? In which browser are you testing?

**Comment by rrutsche** [comment]
@tuguScript sorry, but next time please think of:
1. Giving a more detailed error description
2. Answer other questions as you also want to have answers as quick as possible.

I will close this issue. Re-open it if there is still a problem
