### ISSUE TITLE
When bgImage set dynamically the size is not properly calculated

### ISSUE THREAD

**Issue by jaynakus** [RRutsche/react-parallax#33]
Hi, 
I am trying to change image every time the tab changes. But sometimes pictures are not initialized to full size and somehow it is set according to height. 
Need help

```
<Parallax strength={400} bgImage={bg} bgwidth={'100%'}>
</Parallax>
```

**Comment by rrutsche** [comment]
Hey @jaynakus, sorry for the late response. I will have a look at it

**Comment by rrutsche** [comment]
Hi @jaynakus 
I just published version [1.4.4](https://github.com/RRutsche/react-parallax/releases/tag/v1.4.4). The new version updates dimensions and position correctly after bgImage was changed.
Hope this solves your problem.

And sorry that it took so long. There was a lot to do last month :(

regards, Richard

**Comment by bachrc** [comment]
Thank you for your library, it's really useful !
Though, I have the same problem, even after your last update.

Here's the sample of code :
```js
<div className="jumbocontainer" style={{height: 300}}>
    <Parallax strength={400} bgImage={this.state.image} blur={2} className="parallax" bgwidth={'100%'}>
        <h1>{this.state.nom}</h1>
    </Parallax>
</div>
```

`this.state.image` contains the link to the wanted background image, and when I update it, it doesn't scale automatically. However, when I put a static link, it works like a charm.

I tried some things with `<Background>` but nothing concluent..
Thanks in advance !

**Comment by rrutsche** [comment]
Hi @bachrc,
thanks for your feedback. I just created a test case on codesandbox where the image can be changed dynamically. Can you have a look and maybe change it to your needs so the scaling problem is reproducible? This would be very helpful.

https://codesandbox.io/s/j3jl9oxrw9

Thanks, regards
Richard

**Comment by jaynakus** [comment]
@RRutsche Hey, thanks a lot for solving this issue. Now everything seems smooth.
