### ISSUE TITLE
Alt text on image

### ISSUE THREAD

**Issue by Bram-Zijp** [RRutsche/react-parallax#34]
Hi, could you add an property with which you can define an alt text?

**Comment by rrutsche** [comment]
Hi @Bram-Zijp 
I just published version [1.4.2](https://github.com/RRutsche/react-parallax/releases/tag/v1.4.2) with a new prop `bgImageAlt`.

**Comment by Bram-Zijp** [comment]
Hi @RRutsche 
Thanks for the new prop, it works like a charm. The guys from the SEO department are pleased :)
