### ISSUE TITLE
Background initial 'transform' style computing not working

### ISSUE THREAD

**Issue by ShakurOo** [RRutsche/react-parallax#36]
When I use the `<Background>` component to display my cover image, it appears than the initial css rule transform is `transform: 'translate(-50%, 0)'` where `0` must be a computed value.

So when i scroll a little bit, the img seem's to be jumping to its correct position according the parallax effect. 

It seems the the position is not correctly compute when the component is mount.

For prevent this behavior, I have to hardcoding my default transform style value like this :  
```
<Parallax
    bgStyle={{ transform: 'translate3d(-50%, -35.5482px, 0px)' }}
    strength={400}
    styleName="wrapper"
>
    <Background>
        <img src={this.props.bannerImageUrl} />
    </Background>
</Parallax>
```

**Comment by rrutsche** [comment]
@ShakurOo 
Can you give me an example setup where this is happening? I tried to reproduce but could not see the effect your are describing.
You can just fork this project here on Codesandbox: https://codesandbox.io/s/r0yEkozrw
