### ISSUE TITLE
this.content.getBoundingClientRect() throwing error in Mobile Safari

### ISSUE THREAD

**Issue by mogelbrod** [RRutsche/react-parallax#37]
[This line](https://github.com/RRutsche/react-parallax/blob/ec723c51b6f43a00eb12e75fc1b27b88449c52d8/src/jsx/Parallax.jsx#L207) is reported to be throwing errors on Mobile Safari (v9, v10 & v11):
`TypeError: null is not an object (evaluating 'this.content.getBoundingClientRect')`
 
Our error logs suggest it's happening during unmount (during route transition). I'm guessing `updatePosition` is being called during/after `componentWillUnmount`. A quick solution would be to bail if `this.content` is falsy.

**Comment by rrutsche** [comment]
@mogelbrod Thanks for the report. I will have a look a it. Which version of react are you using in your project?

**Comment by mogelbrod** [comment]
Appreciated!
The current build is running on `react@16.1.1`, but we've been getting reports of the error since October 13 so It's likely present in v16.1.0 (and possibly v16.0.0) as well.

**Comment by rrutsche** [comment]
@mogelbrod 
New version 1.5.1 was just released on npm. It just does an additional check for content node before doing calculations. Hope it solves your issue.
