### ISSUE TITLE
Image onLoad listener added, but not removed while component unmounts

### ISSUE THREAD

**Issue by zespolkropkanadi** [RRutsche/react-parallax#40]
Hi,

Please take a look [here](https://github.com/RRutsche/react-parallax/blob/master/src/modules/Parallax.js#L257). This line of code adds onload event listener to image, which is setting Parallax component state. But when component unmounts (f.e. when changing route) listener is not detached, which causes error:

`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the t component.`

**Comment by rrutsche** [comment]
Thanks for the report. I will have a look.

**Comment by rrutsche** [comment]
The 1.6.1 release should fix the issue
