### ISSUE TITLE
Responsive image optimization for mobile?

### ISSUE THREAD

**Issue by carterchung** [RRutsche/react-parallax#41]
Perhaps add support for srcset? Hoping to get the images to load faster on mobile.
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
I'd be happy to help if you think it's worthwhile.

**Comment by rrutsche** [comment]
Hi, thanks for the request. I will have a look at it and get back to you. Think this should be doable with not to much effort.

**Comment by carterchung** [comment]
Thanks @RRutsche. I added a PR for reference:
https://github.com/RRutsche/react-parallax/pull/42

**Comment by rrutsche** [comment]
I merged the pull request 
https://github.com/RRutsche/react-parallax/pull/42 with some comments. Hope this is working for you now.

**Comment by rrutsche** [comment]
Forgot to say - it's also published on npm - version 1.7.0
