### ISSUE TITLE
Button click or menu

### ISSUE THREAD

**Issue by rohanleach4** [RRutsche/react-parallax#44]
Is it possible to add a button to scroll to another section?

**Comment by rrutsche** [comment]
I think this should not be part of this package. If you want to add scrolling to a specific section on click you could use the package `react-scroll`. The parallax component is just a wrapper. You can add anything you want. Here's a basic example: https://codesandbox.io/s/rym8yvx7m.
Maybe this helps you?

Regards

**Comment by rohanleach4** [comment]
Thanks :-)
