### ISSUE TITLE
reference error when react specified as external

### ISSUE THREAD

**Issue by IevgenNov** [RRutsche/react-parallax#47]
If download react-parallax and react from CDN "ReferenceError: react is not defined" appears
**webpack.config.js**
```javascript
externals: {
    "react": "React",
    "react-dom": "ReactDOM",
    "prop-types": "PropTypes",
    "react-parallax" : "react-parallax"
  },
```

**Comment by rrutsche** [comment]
Hi, did you include `react` in your project dependencies? Or what does your project setup look like?
The idea of excluding this library from the package is that you should install the `react` version of your choice (just once for the whole project) and of course keep the parallax library small.
