### ISSUE TITLE
Is there a way to resize the image?

### ISSUE THREAD

**Issue by Jatapiaro** [RRutsche/react-parallax#48]
When I resize the view, the image don't resize, it just move from left to right.
Is there a way to archive the following effect?: http://santander-universidades.herokuapp.com/santander_universidades_que_es.html

In the following page, try to resize the page and see how the red banner moves.

Thanks.

**Comment by rrutsche** [comment]
Hi,
The image size will be adjusted on window resize so that it always covers the parallax content. 
You could try to set the parallax content height relative to the window width, maybe with a percentage value. This way the image should get smaller. But I fear it won‘t have the exact same behavior as in your example.

**Comment by Jatapiaro** [comment]
I'll give it a try, but how can I do It?
As is a repeated component in the page I did the following component

import React from 'react';
import { Parallax } from 'react-parallax';

```
export default class Banner extends React.Component {

    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div className="parallax-banner">
                <Parallax
                    blur={{ min: -15, max: 15 }}
                    bgImage={this.props.image}
                    strength={300}
                >
                    <div style={{ height: this.props.height, 'backgroundColor': this.props.overlayColor }}>

                        <div className="container">
                            <div className="row banner-text">

                                {
                                    this.props.title && 
                                    <div className="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                        <p className="title">{ this.props.title }</p>
                                        {
                                            this.props.subtitle && 
                                            <p className="subtitle">{this.props.subtitle}</p>
                                        }
                                    </div>
                                }
                            </div>
                        </div>
                        
                    </div>
                </Parallax>
            </div>
        )
    }

}

Banner.defaultProps = {
    'title': undefined,
    'subtitle': undefined,
    'height': '420px',
    'image': require('./../../assets/images/hey.jpg'),
    'overlayColor': 'none'
}
```

The css of it is the following: 

```
.parallax-banner {
    .banner-text {
        bottom: 0;
        position: absolute;
        p {
            text-align: left !important;
        }
        .subtitle {
            color: $white;
            font-family: $open-sans !important;
            font-size: $large !important;
            text-transform: none;
        }
        .title {
            color: $white;
            font-family: $open-sans-bold;
            font-weight: 800;
            font-size: $banner;
            line-height: 1.5;
            text-transform: uppercase;
        }
    }
}
```

Thanks

**Comment by rrutsche** [comment]
Looks like you want to have a fixed height, right? 
I have an idea how to achieve the behavior you asked for. I just created a little example on codesandbox: https://j2x4706219.codesandbox.io/.
You have to use square images or at least images that have a ratio closer to 1x1 (or even portrait format).
This is the code: https://codesandbox.io/s/j2x4706219

**Comment by rrutsche** [comment]
@Jatapiaro Did you have a look at the example above?

**Comment by Jatapiaro** [comment]
Yeah, thank you so much for your help. 
Now I'm just talking to the designers to get all the images in the right format.

THANKS!
