### ISSUE TITLE
backgroundPosition not having any effect

### ISSUE THREAD

**Issue by vpste1** [RRutsche/react-parallax#49]
I can validate bgStyle is working (by adding a margin to the background image for example), however trying to use backgroundPosition fails to have any effect.

I have a large image and trying to centre it and have tried "center center", "50% 50%", etc. with many variations and the image never shifts.

**Comment by rrutsche** [comment]
Hi, as the image is no background image but an <img/> backgroundPosition won't have any effect.

**Comment by rrutsche** [comment]
If you still have questions feel free to reopen the ticket.
