### ISSUE TITLE
Potentially using both an img and div for background image 

### ISSUE THREAD

**Issue by mathew-kurian** [RRutsche/react-parallax#5]
This will allow users to be to rely on more complex css features on div while the img in back will allow for SEO and serve as a fallback.

Great lib btw

**Comment by rrutsche** [comment]
You mean something like this?

``` javascript
<Parallax bgDiv={<div>i want to be translated like the bg image...</div>}>
   ... content
</Parallax>
```

or totally replace bgImage by a div?

**Comment by mathew-kurian** [comment]
I was leaning toward the latter but I feel that your bgDiv technique should do the trick. Essentially, I ended up replacing the <img> tag you had with a <div> as seen here: https://github.com/bluejamesbond/react-parallax/blob/master/src/jsx/Parallax.jsx#L33. This allowed me to control the background options via CSS esp. the style background-size:cover which will allow the background to be scaled to fit the entire div as opposed to having an <img> which will not scale to fit.

**Comment by mathew-kurian** [comment]
Reopening since I accidentally closed the issue.

**Comment by rrutsche** [comment]
Hi @bluejamesbond 
Sorry for the late response. Finally I had time to make some enhancements of the library.
Now you can pass whatever you want to the new `Background` component that is now also exported by the npm package. Children inside this component also get the Parallax positions and you are free to add custom styles. Check the [Readme](https://github.com/RRutsche/react-parallax/blob/master/README.md) for usage.

Also fixed the width/height adjustment on window resize.
Hope that helps.

**Comment by mathew-kurian** [comment]
Thank you. This looks great now!
