### ISSUE TITLE
Parallax Effect On Div or Component

### ISSUE THREAD

**Issue by danielnuwin** [RRutsche/react-parallax#51]
Is it possible to use the effect if I don't use a background image but just the content of a component?

**Comment by rrutsche** [comment]
You can use the `Background` component and insert it as a child of the `Parallax`. Anything that is placed inside it will have the parallax effect.
```javascript
<Parallax>
  <Background>
    Your component or div goes here
  </Background>
</Parallax>
```
The general positioning of this `Background` component is not as exact as the normal background image but you could give it a try.
The other option is to use the new `renderLayer` prop. It has a parameter with the actual relative position. So you can do your own positioning there.
```javascript
<Parallax
  renderLayer={percentage => 
    <div style={
      {top: percentage * 100 /*...or some other calculation with percentage*/}
      }>
    </div>
  }
>
  <div>some content here</div>
</Parallax>
```
