### ISSUE TITLE
Image parallax on device is not working correctly

### ISSUE THREAD

**Issue by pvaritta** [RRutsche/react-parallax#56]
After upgraded to version 2.1.0
When open on device with disabled parallax, bgStyle props is not working
that why background image is not responsive

"react": "16.5.1",
"react-dom": "16.5.1",
"react-parallax": "2.1.0",

![image](https://user-images.githubusercontent.com/18564575/52839206-d0518600-3127-11e9-9971-d3c05a22349c.png)

![image](https://user-images.githubusercontent.com/18564575/52839163-b021c700-3127-11e9-8101-bdb10a9bea77.png)

**Comment by rrutsche** [comment]
I'll have a look at this

**Comment by rrutsche** [comment]
I see you are setting the `bgStyle` attribute but I assume you want to change styles on the background image, right? `bgStyle` is for the `Background` component. Maybe you want to use `bgImageStyle`?

**Comment by pvaritta** [comment]
Hi RRutsche,
Thanks for your answer but I still have the same issue even if I use bgImageStyle instead of bgStyle
Here is my new code that I config `bgImageStyle: { objectFit: 'cover'}` I found that width and height are disappear from the style. But the previous version, width and height are auto generated(depend on device)

**My point is how do I handle this or do you have any suggestion to solve my issue?**

Thank you.

**Comment by rrutsche** [comment]
Almost forgot this one, sorry. 
Did you solve your problem? Otherwise please just create an example implementation on codesandbox which reproduces the issue so I can have a look at. 
Thanks
