### ISSUE TITLE
Need support for TypeScript React projects

### ISSUE THREAD

**Issue by kaleabmelkie** [RRutsche/react-parallax#57]
It'd be really nice to have static types, at least for the core features of the library.

**Comment by rrutsche** [comment]
I'm currently very busy but I will have a look into it soon.

**Comment by rrutsche** [comment]
Hey again, just wanted to let you know that typescript is on its way. It‘s basically finished and just needs some testing.

**Comment by kaleabmelkie** [comment]
That's great news.. thanks!

**Comment by rrutsche** [comment]
While testing goes on you can already install the release candidate if you want.
`yarn add react-parallax@next`

**Comment by rrutsche** [comment]
Typescript is in `master` now and also published with version `3.0.0`

**Comment by kaleabmelkie** [comment]
Thank you. I'll upgrade now.
