### ISSUE TITLE
behaves differently on different screen proportion

### ISSUE THREAD

**Issue by dmatora** [RRutsche/react-parallax#65]
doubling window height makes parallax strength twice lower

![image](https://user-images.githubusercontent.com/647062/70395774-54585f80-1a13-11ea-9201-28f7f076d613.png)

I would expect background image to be entirely visible when you scroll through the page (which would adjust strength dynamicly based on window height/width ratio, or would just calculate percentage differently)

right now is strength is too high, you never see entire image,
if strength is too low, you get white gaps
but even if you calculate perfect strength to see entire image without white gaps, you loose it on different window proportion

**Comment by rrutsche** [comment]
Can you create an example on codesandbox and describe the steps to reproduce? This would help a lot.
Thanks
