### ISSUE TITLE
make demo work on large height/width windows

### ISSUE THREAD

**Issue by goldensunliu** [RRutsche/react-parallax#7]
not sure if it is the link or the demo that is broken at http://rrutsche.github.io/#parallax

**Comment by rrutsche** [comment]
@goldensunliu hm, #worksforme. which browser/device are you using? what is broken exactly?

**Comment by goldensunliu** [comment]
@RRutsche 
![image](https://cloud.githubusercontent.com/assets/1348993/11748415/2e0a2192-9ff6-11e5-97d5-b04104f2d4b6.png)
when i scroll on this page nothing happens:
![image](https://cloud.githubusercontent.com/assets/1348993/11748489/955c6152-9ff6-11e5-8e67-9d5a603df571.png)

**Comment by rrutsche** [comment]
Looks like your Browser width/height is pretty large. Maybe there is not enough content on the demo page. Have you tried it with less window size?

**Comment by goldensunliu** [comment]
@RRutsche that is it. I guess the issue should be the demo should work on large screen sizes.

**Comment by rrutsche** [comment]
I can put in a little more content so that you even have to scroll on large screens. Will do that next time I work on that page.
