### ISSUE TITLE
bgImageSrcSet

### ISSUE THREAD

**Issue by Nadjakoroleva** [RRutsche/react-parallax#71]
Hey Richard,

could you please tell me what syntax should I use for bgImageSrcSet?

Thank you ,
Nadja

**Comment by rrutsche** [comment]
Hi,
syntax description is missing in the description, I should add it. You can pass everything that is officially supported. See here: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images. This can also be combined with `bgImageSizes`
