### ISSUE TITLE
Background image cut doen

### ISSUE THREAD

**Issue by katie-anne-mills** [RRutsche/react-parallax#72]
Hi, thanks so much for developing this. 
No matter how much I change the various attributes passed into the parallax, I only see a section of my background image.
What do I set to see it in full please?
Are there recommended image dimensions?
Many thanks
Katie

**Comment by rrutsche** [comment]
Hi.
A common mistake is that the content (`children`) of the parallax component has not enough height. The height of the image is based on the content. You can check an implementation example here: https://codesandbox.io/embed/r0yEkozrw. If you don't have enough content, you can also set a fixed height:

```javascript
<Parallax bgImage={image1} strength={500}>
    <div style={{ height: 500 }}>
      <div>HTML inside the parallax</div>
    </div>
</Parallax>
```
If this does not solve your issue please send me a minimal example I can have a look at.

**Comment by katie-anne-mills** [comment]
Vielen Dank, Richard! I have shifted to using a carousel but will make a note of this for next time :-).

**Comment by rrutsche** [comment]
Okay, good luck.
