### ISSUE TITLE
Poor rendering result (Text missing)

### ISSUE THREAD

**Issue by TommyLeong** [RRutsche/react-parallax#73]
**Describe the bug**
Used Parallax in my homepage, so I have total 4 `<Parallax>` at the same screen. 

**To Reproduce**
1. Append 4 images (im using Dimension 640 * 360, Resolution 72 * 72)
2. keep scrolling up and down in the screen
3. When you are at bottom of screen, do a quick scroll back to the top of screen
4. Text within the `<Parallax>` is half missing/disappear. It will appear after about 1 second

**Expected behavior**
Should be smooth in scrolling once the page is loaded

**Screenshots**
<img width="1125" alt="textMissing" src="https://user-images.githubusercontent.com/9990179/79019110-22fdc500-7ba8-11ea-985e-11bb6182f813.png">

**Desktop/Smartphone (please complete the following information):**
- macOS Catalina (Version 10.15.4)
- Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Code**
```
<Parallax
          blur={2}
          bgImage={homepageSolution}
          bgImageAlt="coreMsgBackground"
          strength={200}
        >
          <div>
Your desire business solutions
            <div>
              <Button>
                Take my money!
              </Button>
            </div>
          </div>
          <div
            style={{
              height: coreMessagesCardHeight,
            }}
          />
        </Parallax>
```

**Comment by rrutsche** [comment]
Sorry for the late response. I will have a look at it soon. 
Thanks for the detailed description but it would be very cool if you could provide a running example in a repo or codesandbox.

**Comment by rrutsche** [comment]
Does the issue still exist? If yes - please provide a minimal example e.g. on codesandbox.

Thanks

**Comment by TommyLeong** [comment]
Hi @rrutsche,I have not use this library quite sometime. Won't be providing a codesandbox for this moment, shall we just close case until I provide you codesandbox? (:

**Comment by rrutsche** [comment]
Sounds like a plan
