### ISSUE TITLE
Background image is not scaled if the "disabled" property is set by default.

### ISSUE THREAD

**Issue by cheesecase** [RRutsche/react-parallax#81]
**Description**
The background images are not scaled if the "disabled" property is set by default.
For example, if a "reduced motion" version is to be provided for better accessibility, the component should look exactly the same as when the scrolling effect is activated.

**To Reproduce**
Set "disabled" prop to "true" by default.
See lines 178 and 206 in Parallax.tsx
https://github.com/rrutsche/react-parallax/blob/master/src/modules/Parallax.tsx#L197

**Expected behavior**
The component should look exactly the same as when the scrolling effect is activated by default

**Desktop/Smartphone (please complete the following information):**
 - All Browsers

**Comment by rrutsche** [comment]
Yes, you are right. I will have a look.

**Comment by rrutsche** [comment]
This one was open for quite a while. Sorry for that.
But it's fixed now. You can check version v3.2.0 if you like.

I'm going to close this issue. Please reopen it if there is still some issues.
Cheers
