### ISSUE TITLE
Image onLoad callback

### ISSUE THREAD

**Issue by Pareder** [RRutsche/react-parallax#83]
**Is your feature request related to a problem? Please describe.**
I have a problem with calculating the time when image was totally loaded.

**Describe the solution you'd like**
Add additional property `onLoad` and use it as a callback in `this.bgImageRef.onload`.

**Describe alternatives you've considered**
Also you can pass all non registered properties to `img` tag, so the user could pass `onLoad` property which will be transmitted to `img`, but it is not safe.

**Additional context**
Maybe you had the same issue and will propose some workaround.

**Comment by rrutsche** [comment]
Hey, sorry für the late response - I think an onLoad callback would be the best. I will have a look at this in the next few days.

**Comment by rrutsche** [comment]
The latest version `v3.3.0` now has an `onLoad` callback you can use.
