### ISSUE TITLE
Question: What is `percentage` in the `renderLayer` callback?

### ISSUE THREAD

**Issue by zenflow** [RRutsche/react-parallax#87]
This might get labeled a feature request but it's more like a question.
To frame it as a feature request we could say this could be an enhancement to the documentation

What is `percentage` in the `renderLayer` callback?
I know it's a "percentage value of the current position" (as the documentation says) but how exactly (or generally) does it represent the current scroll position?
What is it a "percentage" of?

It's really confusing trying to figure out how to use it since it ranges from 0 (actually `-0`) upward, past 1.0, even before the element has moved out of the viewport.

Thanks!

**Comment by rrutsche** [comment]
Hey, sorry for the delay. This is a tricky question. You might have seen, that the behaviour changed at a point. Originally the percentage (or range) from 0 to 1 behaved differently. It was 0 at the point when the component enters the screen at the bottom. So the anchor for the calculation was at the very top of the parallax container. While scrolling further the point shifted until it was at the bottom of the parallax just before leaving the screen completely. 
But this behaviour made it necessary to increase the image height so there was enough buffer to prevent white space. So yeah the calculation of the range is a bit odd now but for the normal use case it works fine.
