### ISSUE TITLE
Ability to change scroll container

### ISSUE THREAD

**Issue by ghost** [RRutsche/react-parallax#88]
**Is your feature request related to a problem? Please describe.**

This is just requesting the ability to change the scroll container that the parallax observes. 

**Describe the solution you'd like**

A prop that can be passed a ref/className of the overflow container with scroll capabilities.

**Describe alternatives you've considered**
Other parallax libraries.

**Additional context**
Example: https://codesandbox.io/s/parallaxbanner-e5006?file=/src/App.js

**Comment by rrutsche** [comment]
Hey, sorry for the delay. Isn't the `parent` prop the one you are looking for?

**Comment by lucas-santosP** [comment]
@rrutsche  But what would be the syntax to use the `parent` prop? I'm searching an example in the docs and issues here but I didn't found it. I'm trying to use with Typescript and I'm having to do a `querySelector` and type assertion to `HTMLElement`, which is working but I don't know if it's actually correct.

```ts
parent={document.querySelector("#content") as HTMLElement}
```

**Comment by rrutsche** [comment]
Hey. This kitchen sink has an example implementation: https://github.com/rrutsche/react-parallax/blob/master/src/kitchensink/p3.tsx#L76
Does this help?

Cheers
