### ISSUE TITLE
Compatibility with react 17.0.1

### ISSUE THREAD

**Issue by frozar** [RRutsche/react-parallax#89]
**Describe the bug**
The current version of `react-parallax` is not compatible with latest version of react `17.0.1`.

**To Reproduce**
1. Type command: `npx create-next-app react-parallax-issue`
2. Go to directory react-parallax-issue: `cd react-parallax-issue`
3. Try to install react-parallax: `npm i react-parallax`
4. You should get this error message:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-parallax-issue@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.x.x" from react-parallax@3.2.0
npm ERR! node_modules/react-parallax
npm ERR!   react-parallax@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/frozar/.npm/eresolve-report.txt for a full report.
```

**Expected behavior**
react-parallax should be compatible with `react@17.0.1`.

**Desktop/Smartphone (please complete the following information):**
 - OS and Device: Ubuntu 18.04

**Code and/or example**
Repository example: https://github.com/frozar/react-parallax-issue

**Comment by rrutsche** [comment]
Should be fixed in version `v3.2.1`. I just published it on npm.
If there is still an issue feel free to reopen the ticket.

**Comment by frozar** [comment]
Wow, you're super reactive, thank you for the update, it works on my side.

Just to let you know, when I install react-parallax on my fresh new repository, I get the following warning messages:
```
$ npm i react-parallax
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'postcss@8.1.7',
npm WARN EBADENGINE   required: { node: '^10 || ^12 || >=14' },
npm WARN EBADENGINE   current: { node: 'v13.7.0', npm: '7.5.4' }
npm WARN EBADENGINE }
```

**Comment by rrutsche** [comment]
Yeah thanks for the info 👍🏼. I will have a look.
